### ISSUE TITLE
OCI 배포 GHCR 패키징 github action

### ISSUE THREAD

**Issue by rhquddnr95** [dearmoment-team/dear-moment-backend#37]
##  이슈 내용

> 이슈 내용 작성

<br>

##  작업 사항

- [ ] 해당 이슈의 작업사항

<br>

## 기타사항

<br>

**Comment by ksooo091** [comment]
컨테이너 빌드, 푸시는 Actions 사용해주세요 https://docs.github.com/ko/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-a-registry-using-a-personal-access-token

**Comment by ksooo091** [comment]
@rhquddnr95  
.github/workflows/docker-publish.yml 파일에서
지금 ghcr 로그인, 컨테이너 빌드 푸시를 커맨드로 실행하고 계시는 부분을  
링크에 드린 방법처럼 actions를 사용해 
```
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
```
처럼 사용하는게 좋다는 의미입니다.  
특히 빌드시 캐시 사용등을 고려하면 builx actions 사용을 추천드립니다.
